//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFGUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fwavesEntities : DbContext
    {
        public fwavesEntities()
            : base("name=fwavesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetTotalHeight_Result> GetTotalHeight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalHeight_Result>("GetTotalHeight");
        }
    }
}
